apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-cf1i
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-cf1i@sha256:3d2b2978b81492376c6422aef1bb891069790fe36c137fd85f1dfb7a49d3d567
        name: my-nodejs
        resources: {}
status: {}
