apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-rmrs
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-rmrs@sha256:1578065a1a1a454a1a329b0f167665bd1c94303b6a189f13750314cabbf6e6c3
        name: my-python
        resources: {}
status: {}
